# 商品页订单详情
query GoodsOrders($sort: String, $limit: Int, $start: Int, $where: JSON) {
  orders: ordersConnection(sort: $sort, limit: $limit, start: $start, where: $where) {
    values {
      id
      name
    }
    aggregate {
      count
      totalCount
    }
  }
}

# 商品页 order 对应的商品列表
# TODO: commodities 需要分页
query OrderCommodities($id: ID!) {
  order(id: $id) {
    id
    commodities(start: 0, limit: 1000) {
      id
      code
      commodity_type {
        id
        name
      }
      warehouse {
        name
        id
      }
      createdAt
      user {
        username
      }
      accessories
    }
  }
}

# 商品页 order 出库弹窗对应的商品列表
query OrderCommoditiesSimple($id: ID!, $start: Int, $limit: Int) {
  commodities: commoditiesConnection(start: $start, limit: $limit, where: { order: $id }) {
    values {
      id
      code
      commodity_type {
        id
        name
      }
      warehouse {
        name
        id
      }
    }
    aggregate {
      count
      totalCount
    }
  }
}

# 查询商品分类
query CommodityTypesSelect {
  types: commodityTypes(start: 0, limit: 1000) {
    id
    name
  }
}

# 查询仓库信息
query WarehousesSelect {
  pos: warehouses(start: 0, limit: 1000) {
    id
    name
  }
}

# 商品出库
mutation CommodityExWarehouse($input: outboundCommodityInput) {
  commodities: outboundCommodity(input: $input) {
    data
  }
}
