fragment orderHistory on OrderMaterialHistory {
  id
  createdAt
  updatedAt
  order_id {
    id
  }
  remark
  attachment_desc
  content
  user {
    username
  }
}

query OMHrys($limit: Int, $start: Int, $where: JSON) {
  hrys: orderMaterialHistories(sort: "createdAt:desc", limit: $limit, start: $start, where: $where) {
    ...orderHistory
  }
}

query OMHry($id: ID!) {
  hry: orderMaterialHistory(id: $id) {
    ...orderHistory
  }
}

query OrderMaterials($limit: Int, $start: Int, $where: JSON) {
  orderMaterials(limit: $limit, start: $start, where: $where, sort: "createdAt:desc") {
    id
    createdAt
    updatedAt
    order_id {
      id
    }
    material
    amount
    model
    user {
      id
      username
    }
  }
}

query OrderMaterialsConnection($limit: Int, $start: Int, $where: JSON) {
  orderMaterialsConnection(limit: $limit, start: $start, where: $where, sort: "createdAt:desc") {
    values {
      id
      createdAt
      updatedAt
      order_id {
        id
      }
      material
      amount
      model
      user {
        id
        username
      }
    }

    aggregate {
      count
    }
  }
}

mutation CreateOrderMaterials($input: CreateOrderMaterialsInput) {
  batchCreateMaterials(input: $input) {
    order_id
  }
}

mutation UpdateOrderMaterials($input: UpdateOrderMaterialsInput) {
  batchUpdateMaterials(input: $input) {
    order_id
  }
}

query OrderMaterialHistoriesConnection($limit: Int, $start: Int, $id: ID) {
  orderMaterialHistoriesConnection(limit: $limit, start: $start, where: { order_id: $id }, sort: "createdAt:desc") {
    values {
      id
      createdAt
      updatedAt
      remark
      user {
        username
      }
      attachment_desc
      content
      attachment {
        id
        url
      }
    }
    aggregate {
      count
    }
  }
}

# Materials select
query Materials {
  materials(limit: 1000, start: 0) {
    id
    name
  }
}
