fragment orderHistory on OrderMaterialHistory {
  id
  createdAt
  updatedAt
  order_id {
    id
  }
  remark
  attachment_desc
  content
  user {
    username
  }
}

query OMHrys($sort: String, $limit: Int, $start: Int, $where: JSON) {
  hrys: orderMaterialHistories(sort: $sort, limit: $limit, start: $start, where: $where) {
    ...orderHistory
  }
}

query OMHry($id: ID!) {
  hry: orderMaterialHistory(id: $id) {
    ...orderHistory
  }
}

query OrderMaterials($limit: Int, $start: Int, $where: JSON, $sort: String) {
  orderMaterials(limit: $limit, start: $start, where: $where, sort: $sort) {
    id
    createdAt
    updatedAt
    order_id {
      id
    }
    material
    amount
    model
    user {
      id
      username
    }
  }
}
