fragment order on Order {
  id
  name
  createdAt
  updatedAt
  detail
  amount
  delivery_time
  user {
    username
  }
}

query Orders($sort: String, $limit: Int, $start: Int, $where: JSON) {
  orders(sort: $sort, limit: $limit, start: $start, where: $where) {
    ...order
  }
}

query Order($id: ID!) {
  order(id: $id) {
    ...order
  }
}

query OrdersConnection($sort: String, $limit: Int, $start: Int, $where: JSON) {
  ordersConnection(sort: $sort, limit: $limit, start: $start, where: $where) {
    values {
      ...order
    }
    aggregate {
      count
    }
  }
}

mutation CreateOrder($data: OrderInput) {
  createNewOrder(input: { data: $data }) {
    order {
      ...order
    }
  }
}

mutation UpdateOrder($id: ID!, $data: editOrderInput) {
  updateOldOrder(input: { where: { id: $id }, data: $data }) {
    order {
      ...order
    }
  }
}

query OrderHistoriesConnection($sort: String, $limit: Int, $start: Int, $id: ID!) {
  orderHistoriesConnection(sort: $sort, limit: $limit, start: $start, where: { order: $id }) {
    values {
      id
      createdAt
      updatedAt
      detail
      amount
      delivery_time
      order {
        id
        name
      }
      user {
        username
      }
    }
    aggregate {
      count
    }
  }
}
