fragment order on Order {
  id
  created_at
  updated_at
  detail
  amount
  delivery_time
  created_by {
    username
  }
  updated_by {
    username
  }
}

query Orders($sort: String, $limit: Int, $start: Int, $where: JSON) {
  orders(sort: $sort, limit: $limit, start: $start, where: $where) {
    ...order
  }
}

query Order($id: ID!) {
  order(id: $id) {
    ...order
  }
}
